// golden-paths/h1-foundation/web-application/skeleton/frontend/react/src/App.tsx
import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '2rem' }}>
      <h1>${{ values.appName }}</h1>
      <p>Welcome to your new application.</p>
      <button onClick={() => setCount((c) => c + 1)}>Count: {count}</button>
    </div>
  );
}

export default App;

// golden-paths/h1-foundation/web-application/skeleton/frontend/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <div style="max-width: 800px; margin: 0 auto; padding: 2rem">
    <h1>${{ values.appName }}</h1>
    <p>Welcome to your new application.</p>
    <button @click="count++">Count: {{ count }}</button>
  </div>
</template>
